servicetitle: 'our services'
servicesubtitle: 'Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit'
servicetitlestyle: 'heading2--section'
serviceitems: 
 - icon: 'bi bi-activity'
   heading: 'Nesciunt Mete'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Provident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'
 - icon: 'bi bi-broadcast'
   heading: 'Eosle Commodi'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Ut autem aut autem non a. Sint sint sit facilis nam iusto sint. Libero corrupti neque eum hic non ut nesciunt dolorem.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'
 - icon: 'bi bi-easel'
   heading: 'Ledo Markt'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Ut excepturi voluptatem nisi sed. Quidem fuga consequatur. Minus ea aut. Vel qui id voluptas adipisci eos earum corrupti.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'
 - icon: 'bi bi-bounding-box-circles'
   heading: 'Asperiores Commodit'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Non et temporibus minus omnis sed dolor esse consequatur. Cupiditate sed error ea fuga sit provident adipisci neque.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'
 - icon: 'bi bi-calendar4-week'
   heading: 'Velit Doloremque'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Cumque et suscipit saepe. Est maiores autem enim facilis ut aut ipsam corporis aut. Sed animi at autem alias eius labore.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'
 - icon: 'bi bi-chat-square-text'
   heading: 'Dolori Architecto'
   url: 'https://bootstrapmade.com/demo/templates/EstateAgency/service-details.html'
   paragraph: 'Hic molestias ea quibusdam eos. Fugiat enim doloremque aut neque non et debitis iure. Corrupti recusandae ducimus enim.'
   headingstyle: 'heading3--card'
   paragraphstyle: 'paragraph--card'